# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'SwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftDemo
  
  pod 'Alamofire'   #网络库 类似 AFNetWork
  pod 'Kingfisher'  #图片库 类似 SDWebImage
  pod 'SwiftyJSON'  #JSON库
  pod 'SnapKit'     #布局   Swift版的Masonry

end
